# Generated by Django 6.1.1 on 2026-09-27 16:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('github', 'GitHub')], max_length=20)),
                ('repository_url', models.URLField(blank=True, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
